sudo: required

services:
  - docker

before_install: 
  - docker build -t jonny5592/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true jonny5592/react-test npm test

after_success:
  # Build Docker Images
  - docker build -t jonny5592/fib-client ./client
  - docker build -t jonny5592/fib-nginx ./nginx
  - docker build -t jonny5592/fib-server ./server
  - docker build -t jonny5592/fib-worker ./worker 
  # Login To Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push Images To Docker Hub
  - docker push jonny5592/fib-client
  - docker push jonny5592/fib-nginx
  - docker push jonny5592/fib-server
  - docker push jonny5592/fib-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Fibonacci"
  env: "Fibonacci-env"
  bucket_name: "elasticbeanstalk-us-east-1-879238464235"
  bucket_path: "Fibonacci"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY