sudo: required

services:
  - docker

before_install: 
  - docker build -t jonny5592/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true jonny5592/react-test npm test

after_success:
  - docker build -t jonny5592/fib-client ./client
  - docker build -t jonny5592/fib-nginx ./nginx
  - docker build -t jonny5592/fib-server ./server
  - docker build -t jonny5592/fib-worker ./worker 

